const translations = {
  en:{
  home: "Home",
  about: "About",
  service: "Service",
  work: "Work",
  blog: "Blog",
  contact: "Contact",
  downloadCV: "Download CV",
  getInTouch: "Get In Touch",
  contactMe: "Contact Me",
  sendMessage: "Send Message",
  aboutTitle: "About Me",
  aboutName: "Yahya Abosolyman",
  aboutDetails: "I'm a frontend developer with more than 4 years of experience. If you need to receive responsive, pixel-perfect, and cross-browser websites, I'm the developer you're looking for.",
  birthday: "Birthday: 29 Dec 2002",
  degree: "Degree: Bachelor's",
  website: "Website: www.nasraldaya.com",
  mail: "Mail: nasrmnldaya@gmail.com",
  phone: "Phone: +970 59 934 1729",
  linkedin: "Linkedin: @nasraldaya",
  study: "Study: Islamic University of Gaza",
  freelance: "Freelance: Available",
  whatIDo: "What I Do",
  serviceTitle: "Service",
  services: [
    {
      name: "Website",
      description: "Viamus ravida surna eveti semeni conse convallis. Tristique busio the nivite dianne one nivami",
    },
    {
      name: "Seo Marketing",
      description: "Viamus ravida surna eveti semeni conse convallis. Tristique busio the nivite dianne one nivami",
    },
    {
      name: "Ecommerce",
      description: "Viamus ravida surna eveti semeni conse convallis. Tristique busio the nivite dianne one nivami",
    },
    {
      name: "Graphic design",
      description: "Viamus ravida surna eveti semeni conse convallis. Tristique busio the nivite dianne one nivami",
    },
    {
      name: "Digital Marketing",
      description: "Viamus ravida surna eveti semeni conse convallis. Tristique busio the nivite dianne one nivami",
    },
    {
      name: "Social Media",
      description: "Viamus ravida surna eveti semeni conse convallis. Tristique busio the nivite dianne one nivami",
    },
  ],
  recentWork: "Recent Work Completed",
  workShowcase: "Work Showcase",
  myBlog: "My Blog",
  currentNews: "Current News",
  blogItems: [
    {
      category: "Web Design",
      date: "18 Dec, 2021",
      title: "Developer Watch Out For These Burnout Symptoms",
    },
    {
      category: "Social Media",
      date: "18 Dec, 2021",
      title: "From Perfect To Positive",
    },
    {
      category: "Mobile Design",
      date: "18 Dec, 2021",
      title: "Developer Watch Out For These Burnout Symptoms",
    },
    {
      category: "Desktop Design",
      date: "18 Dec, 2021",
      title: "From Perfect To Positive",
    },
  ],
  getInTouchTitle: "Get In Touch",
  contactMeTitle: "Contact Me",
  createFuture: "Let's Create The Future",
  availableFor: "I'm available for commissions and collaborations. and I'am excited to hear from you about new project",
  contactInfo: {
    phone: "+970 59 324 1570",
    email: "yabosolyman@gmail.com",
    username: "@yabosolyman",
    address: "Palestine, Gaza, Elnaser Street",
  }
},
ar:{
  home: "الرئيسية",
  about: "حول",
  service: "خدمات",
  work: "أعمال",
  blog: "مدونة",
  contact: "اتصال",
  downloadCV: "تحميل السيرة الذاتية",
  getInTouch: "تواصل معنا",
  contactMe: "اتصل بي",
  sendMessage: "إرسال الرسالة",
  aboutTitle: "حولني",
  aboutName: "يحيى أبو سليمان",
  aboutDetails: "أنا مطور واجهات أمامية مع أكثر من 4 سنوات خبرة. إذا كنت تريد مواقع متجاوبة، دقيقة ومتوافقة مع جميع المتصفحات، فأنا المطور الذي تبحث عنه.",
  birthday: "تاريخ الميلاد: 29 ديسمبر 2002",
  degree: "المؤهل: بكالوريوس",
  website: "الموقع الإلكتروني: www.nasraldaya.com",
  mail: "البريد الإلكتروني: nasrmnldaya@gmail.com",
  phone: "الهاتف: +970 59 934 1729",
  linkedin: "لينكدإن: @nasraldaya",
  study: "الدراسة: الجامعة الإسلامية غزة",
  freelance: "العمل الحر: متاح",
  whatIDo: "ما الذي أفعله",
  serviceTitle: "الخدمات",
  services: [
    {
      name: "مواقع إلكترونية",
      description: "فياموسرافي دا سورنا إفيتي سيميني كونس كونفاليس. تريستيك بوسيو ذي نيفيتي ديان وان نيفامي",
    },
    {
      name: "تسويق محركات البحث",
      description: "فياموسرافي دا سورنا إفيتي سيميني كونس كونفاليس. تريستيك بوسيو ذي نيفيتي ديان وان نيفامي",
    },
    {
      name: "تجارة إلكترونية",
      description: "فياموسرافي دا سورنا إفيتي سيميني كونس كونفاليس. تريستيك بوسيو ذي نيفيتي ديان وان نيفامي",
    },
    {
      name: "تصميم جرافيكي",
      description: "فياموسرافي دا سورنا إفيتي سيميني كونس كونفاليس. تريستيك بوسيو ذي نيفيتي ديان وان نيفامي",
    },
    {
      name: "التسويق الرقمي",
      description: "فياموسرافي دا سورنا إفيتي سيميني كونس كونفاليس. تريستيك بوسيو ذي نيفيتي ديان وان نيفامي",
    },
    {
      name: "وسائل التواصل الاجتماعي",
      description: "فياموسرافي دا سورنا إفيتي سيميني كونس كونفاليس. تريستيك بوسيو ذي نيفيتي ديان وان نيفامي",
    },
  ],
  recentWork: "الأعمال الحديثة المنجزة",
  workShowcase: "عرض الأعمال",
  myBlog: "مدونتي",
  currentNews: "الأخبار الحالية",
  blogItems: [
    {
      category: "تصميم ويب",
      date: "18 ديسمبر 2021",
      title: "المطورون احذروا أعراض الإرهاق",
    },
    {
      category: "وسائل التواصل",
      date: "18 ديسمبر 2021",
      title: "من الكمال إلى الإيجابية",
    },
    {
      category: "تصميم الجوال",
      date: "18 ديسمبر 2021",
      title: "المطورون احذروا أعراض الإرهاق",
    },
    {
      category: "تصميم سطح المكتب",
      date: "18 ديسمبر 2021",
      title: "من الكمال إلى الإيجابية",
    },
  ],
  getInTouchTitle: "تواصل معنا",
  contactMeTitle: "اتصل بي",
  createFuture: "لنصنع المستقبل",
  availableFor: "أنا متاح للطلبات والتعاونات، ويسعدني سماع أخبار مشاريعك الجديدة.",
  contactInfo: {
    phone: "+970 59 324 1570",
    email: "yabosolyman@gmail.com",
    username: "@yabosolyman",
    address: "فلسطين، غزة، شارع النصير",
  }
}
};